In [94]:
import pandas as pd

# Creating a DataFrame from a dictionary :

In [95]:
data = {
     "Name" :  ["Anu","Rahul","Priya"],
    "Age"  : [21,22,21],
    "Mark"  : [85,90,88]
}
df = pd.DataFrame(data)
df

    Name  Age  Mark
0    Anu   21    85
1  Rahul   22    90
2  Priya   21    88

# Creating a DataFrame from a list :

In [96]:
data = [
    ["Anu",21,85],
    ["Rahul",22,90],
    ["Priya",21,88]
]
df = pd.DataFrame(data ,columns =["Name","Age","Mark"])
df

    Name  Age  Mark
0    Anu   21    85
1  Rahul   22    90
2  Priya   21    88

# Creating a DataFrame with a custom index :

In [97]:
data = {
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
}
df = pd.DataFrame(data , index = ["s1","s2","s3"])
df

     Name  Mark
s1    Anu    85
s2  Rahul    90
s3  Priya    88

# Displaying Columns - df.columns :

In [98]:
df.columns

Index(['Name', 'Mark'], dtype='object')

# Selecting a single column :

In [99]:
df["Name"]

s1      Anu
s2    Rahul
s3    Priya
Name: Name, dtype: object

# Selecting multiple column :

In [100]:
df[["Name","Mark"]]

     Name  Mark
s1    Anu    85
s2  Rahul    90
s3  Priya    88

# Selecting rows using iloc :

In [101]:
df.iloc[0]

Name    Anu
Mark     85
Name: s1, dtype: object

# Selecting multiple rows :

In [102]:
df.iloc[:2]

     Name  Mark
s1    Anu    85
s2  Rahul    90

# Selecting a particular row and column :

In [103]:
df.iloc[1,1]

np.int64(90)

# Selecting rows using loc :

In [104]:
data = {
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
}
df = pd.DataFrame(data , index =["s1","s2","s3"])
df.loc["s2"]

Name    Rahul
Mark       90
Name: s2, dtype: object

# Adding a new column :

In [105]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
})
df["Grade"] = ["A","A+","A"]
df

    Name  Mark Grade
0    Anu    85     A
1  Rahul    90    A+
2  Priya    88     A

# Modifying a Existing column :

In [106]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
})
df["Mark"] = [90,95,92]
df

    Name  Mark
0    Anu    90
1  Rahul    95
2  Priya    92

# Adding a new row :

In [107]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
})
df.loc[3] = ["Arun",80]
df

    Name  Mark
0    Anu    85
1  Rahul    90
2  Priya    88
3   Arun    80

# Removing a column - drop() :

In [108]:
df = df.drop("Mark" ,axis = 1)
df

    Name
0    Anu
1  Rahul
2  Priya
3   Arun

# Removing a row - drop() :

In [109]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,90,88]
})
df.drop(1)

    Name  Mark
0    Anu    85
2  Priya    88

# DataFrame shape - df.shape :

In [110]:
df.shape

(3, 2)

# DataFrame size - df.size :

In [111]:
df.size

6

# Number of rows and columns :

In [112]:
len(df)  # number of rows

3

In [113]:
len(df.columns) # number of column

2

# DataTypes - df.dtypes :

In [114]:
df.dtypes

Name    object
Mark     int64
dtype: object

# Index and Columns :

In [115]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [116]:
df.columns

Index(['Name', 'Mark'], dtype='object')

# Basic Information - Info() :

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Mark    3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

# Basic Statistics - describe() :

In [118]:
df = pd.DataFrame({
    "Mark" : [70,80,90,85,75]
})
df.describe()

            Mark
count   5.000000
mean   80.000000
std     7.905694
min    70.000000
25%    75.000000
50%    80.000000
75%    85.000000
max    90.000000

# Filtering rows :

In [119]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya","Arun"],
     "Mark"  : [85,90,45,75]
})
df[df["Mark"] > 80]

    Name  Mark
0    Anu    85
1  Rahul    90

# Sorting a dataframe :

# Ascending order

In [120]:
df = df.sort_values("Mark")
df

    Name  Mark
2  Priya    45
3   Arun    75
0    Anu    85
1  Rahul    90

# Descending order

In [121]:
df = df.sort_values("Mark" ,ascending = False)
df

    Name  Mark
1  Rahul    90
0    Anu    85
3   Arun    75
2  Priya    45

# Checking for missing values - isna() :

In [122]:
import pandas as pd

In [123]:
import numpy as np

In [124]:
df = pd.DataFrame({
     "Name" :  ["Anu","Rahul","Priya"],
     "Mark"  : [85,np.nan,90]
})
df.isna()

    Name   Mark
0  False  False
1  False   True
2  False  False

# Counting missing values :

In [125]:
df.isna().sum()

Name    0
Mark    1
dtype: int64

# Filling missing values - fillna()

In [126]:
df["Mark"] = df["Mark"].fillna(0)
df

    Name  Mark
0    Anu  85.0
1  Rahul   0.0
2  Priya  90.0

# Removing rows with missing values : dropna() :

In [127]:
df.dropna()
df

    Name  Mark
0    Anu  85.0
1  Rahul   0.0
2  Priya  90.0

# Viewing first and last row - head() and tail() :

# head()

In [128]:
df.head()

    Name  Mark
0    Anu  85.0
1  Rahul   0.0
2  Priya  90.0

In [129]:
df.head(2)

    Name  Mark
0    Anu  85.0
1  Rahul   0.0

# tail()

In [130]:
df.tail()

    Name  Mark
0    Anu  85.0
1  Rahul   0.0
2  Priya  90.0

In [131]:
df.tail(2)

    Name  Mark
1  Rahul   0.0
2  Priya  90.0

# Data Frame Arithmetic :

In [133]:
df["Mark"] = df["Mark"] + 5
df

    Name  Mark
0    Anu  90.0
1  Rahul   5.0
2  Priya  95.0

In [134]:
df["Mark"] = df["Mark"] - 5
df

    Name  Mark
0    Anu  85.0
1  Rahul   0.0
2  Priya  90.0

In [135]:
df["Mark"] = df["Mark"] * 2
df

    Name   Mark
0    Anu  170.0
1  Rahul    0.0
2  Priya  180.0