In [25]:
import pandas as pd

In [26]:
df1 = pd.DataFrame({
    "id" : [1,2,3,4],
    "Name" : ["Harshad","Monu","Fanu","Ayan"],
    "Roll_no" : [10,20,30,40]
})
df2 = pd.DataFrame({
    "id" : [1,2,3,5],
    "Marks" : [25,56,89,50],
    "Tag" : [11,21,31,41]
})
merged_df = pd.merge(df1,df2,on = "id")
merged_df

   id     Name  Roll_no  Marks  Tag
0   1  Harshad       10     25   11
1   2     Monu       20     56   21
2   3     Fanu       30     89   31

# Inner join

In [27]:
pd.merge(df1,df2, on = "id",how = "inner")

   id     Name  Roll_no  Marks  Tag
0   1  Harshad       10     25   11
1   2     Monu       20     56   21
2   3     Fanu       30     89   31

# Left join

In [28]:
pd.merge(df1,df2, on = "id",how = "left")

   id     Name  Roll_no  Marks   Tag
0   1  Harshad       10   25.0  11.0
1   2     Monu       20   56.0  21.0
2   3     Fanu       30   89.0  31.0
3   4     Ayan       40    NaN   NaN

# Right join

In [29]:
pd.merge(df1,df2, on = "id",how = "right")

   id     Name  Roll_no  Marks  Tag
0   1  Harshad     10.0     25   11
1   2     Monu     20.0     56   21
2   3     Fanu     30.0     89   31
3   5      NaN      NaN     50   41

# Outer join

In [30]:
pd.merge(df1,df2, on = "id",how = "outer")

   id     Name  Roll_no  Marks   Tag
0   1  Harshad     10.0   25.0  11.0
1   2     Monu     20.0   56.0  21.0
2   3     Fanu     30.0   89.0  31.0
3   4     Ayan     40.0    NaN   NaN
4   5      NaN      NaN   50.0  41.0

# Merge on different column names

In [31]:
df1 = pd.DataFrame({
    "id" : [1,2,3,4],
    "Name" : ["Harshad","Monu","Fanu","Ayan"],
    "Roll_no" : [10,20,30,40]
})
df2 = pd.DataFrame({
    "student_id" : [1,2,3,5],
    "Marks" : [25,56,89,50],
    "Tag" : [11,21,31,41]
})
merged_df = pd.merge(df1,df2,left_on = "id",right_on = "student_id")
merged_df

   id     Name  Roll_no  student_id  Marks  Tag
0   1  Harshad       10           1     25   11
1   2     Monu       20           2     56   21
2   3     Fanu       30           3     89   31

# Concatenation

In [32]:
pd.concat([df1,df2],axis = 0)

    id     Name  Roll_no  student_id  Marks   Tag
0  1.0  Harshad     10.0         NaN    NaN   NaN
1  2.0     Monu     20.0         NaN    NaN   NaN
2  3.0     Fanu     30.0         NaN    NaN   NaN
3  4.0     Ayan     40.0         NaN    NaN   NaN
0  NaN      NaN      NaN         1.0   25.0  11.0
1  NaN      NaN      NaN         2.0   56.0  21.0
2  NaN      NaN      NaN         3.0   89.0  31.0
3  NaN      NaN      NaN         5.0   50.0  41.0

In [33]:
pd.concat([df1,df2],axis = 1)

   id     Name  Roll_no  student_id  Marks  Tag
0   1  Harshad       10           1     25   11
1   2     Monu       20           2     56   21
2   3     Fanu       30           3     89   31
3   4     Ayan       40           5     50   41

# Apply

In [48]:
mark = pd.Series([30,50,45,70,90])
def grade(x):
    if x == 50 :
        return "Perfect match"
    else:
        return "Not match"
mark.apply(grade)

0        Not match
1    Perfect match
2        Not match
3        Not match
4        Not match
dtype: object

# Apply using Lambda Function

In [35]:
mark = pd.Series([30,50,45,70,90])
grade = mark.apply(lambda x:x * 2)
grade

0     60
1    100
2     90
3    140
4    180
dtype: int64

# Apply on dataframe columns

In [46]:
mark = pd.DataFrame({
    "Physics" : [30,50,29,70,90],
    "Biology" : [20,40,60,80,100],
    "Chemistry" : [25,35,45,55,67]
})
print(mark.apply(lambda x:x.mean()))

Physics      53.8
Biology      60.0
Chemistry    45.4
dtype: float64

In [47]:
mark.mean()

Physics      53.8
Biology      60.0
Chemistry    45.4
dtype: float64